spring:
  application:
    name: mybatis-plus-springboot
  #数据库信息
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatisplus?useSSL=false&serverTimezone=UTC&characterEncoding=utf-8&useUnicode=true
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource


#mybatis-plus
mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.qf.mybatisplus.springboot.pojo
  configuration:
    map-underscore-to-camel-case: true

#日志配置
logging:
  level:
    com.qf.mybatisplus.springboot.mapper: debug

